version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.7.2
    steps:
      - checkout
      - run:
          name: Install All Dependencies
          command: cd server && yarn install
      - run:
          name: Build TSC Application
          command: cd server && yarn build
  test:
    docker:
      - image: cimg/node:21.7.2
    steps:
      - checkout
      - run:
          name: Install All Dependencies
          command: cd server && yarn install
      - run:
          name: Run All Tests
          command: cd server && yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
